dashman:
  build: ./
  ports:
   - "5050:5050"
  volumes:
   - .:/code
  environment:
    # Put variables in .env file
    - DD_API_KEY=$DD_API_KEY
    - DD_APP_KEY=$DD_APP_KEY
    - DD_DEFAULT_DASH=$DD_DEFAULT_DASH
